Web/Startup/Models/HttpClientDo.cs
using System.Net.Http;

namespace Startup.Models
{
    public class HttpClientDo
    {
        public HttpClient HttpClient {get;set;}
        public string Name {get;set;}
    }
}

Web/Startup/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Startup.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Startup/Controllers/SequenceController.cs
using Microsoft.AspNetCore.Mvc;
using Startup.Config;
using Startup.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Startup.Controllers
{
    public class SequenceController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly MachinesConfig _machinesConfig;

        public SequenceController(IHttpClientFactory httpClientFactory, MachinesConfig machinesConfig)
        {
            _httpClientFactory = httpClientFactory;
            _machinesConfig = machinesConfig;
        }

        public async Task<IActionResult> Index()
        {
            var resultViewModel = new SequenceViewModel
            {
                SequenceCalculationInformation = new List<CalculationInformation>()
            };

            var listOfMachines =
                new List<HttpClientDo>();

            _machinesConfig.Machines.ForEach((machine) =>
            {
                listOfMachines.Add(new HttpClientDo
                {
                    Name = machine.Name,
                    HttpClient = _httpClientFactory.CreateClient(machine.Name)
                });
            });

            Random randomNumberGenerator = new Random();

            var fibonacciNumbers = new List<int>();

            foreach (var machine in listOfMachines)
            {
                int randomNumber = randomNumberGenerator.Next(int.MaxValue / 2);
                string closestNumberAsString =
                await machine.HttpClient.GetStringAsync($"fibonacci-sequence/closest-sequence-number?number={randomNumber}");

                fibonacciNumbers.Add(int.Parse(closestNumberAsString));
            }

            int sequenceEnd = fibonacciNumbers.Max();
            int sequenceStart = fibonacciNumbers.Min();

            resultViewModel.SequenceStartPoint = sequenceStart;
            resultViewModel.SequenceEndPoint = sequenceEnd;

            int currentSequenceNumber = sequenceStart;
            var machineInUse = listOfMachines.First();

            while (currentSequenceNumber < sequenceEnd)
            {
                string calculatedSequenceNumberAsString =
                    await machineInUse
                    .HttpClient
                    .GetStringAsync($"fibonacci-sequence/next-sequence-number?currentSequenceNumber={currentSequenceNumber}");

                int calculatedSequenceNumber = int.Parse(calculatedSequenceNumberAsString);

                if (calculatedSequenceNumber != sequenceEnd)
                    resultViewModel.SequenceCalculationInformation.Add(
                    new CalculationInformation
                    {
                        Number = calculatedSequenceNumber,
                        Machine = machineInUse.Name
                    });

                currentSequenceNumber = calculatedSequenceNumber;

                machineInUse = listOfMachines
                    .OrderBy(x => Guid.NewGuid())
                    .First(x => x.Name != machineInUse.Name);
            };

            return View(resultViewModel);
        }
    }
}

Web/Startup/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Main Page";
}

<div>
    <h1>Welcome</h1>
    <p>
        You have landed in a Fibunacci numbers calculator. Click 
        <a asp-area="" asp-controller="Sequence" asp-action="Index">kere</a> to navigate to sequence page.
    </p>
</div>

Web/Startup/Views/Sequence/Index.cshtml
@model Startup.Models.SequenceViewModel

@{
    ViewData["Title"] = "Sequence Page";
}

<div class="text-center">
    <h1 class="display-4">Sequence</h1>
    <p>This calculator uses three difference machines to calculate the start and end values for a Fibunacci sequence as well as sequence in between those numbers. 
    Bellow please find calculated sequence</p>

    <h2>Sequence - [@Model.SequenceStartPoint.ToString("N0"), @Model.SequenceEndPoint.ToString("N0")]</h2>
    <h3>Sequence numbers in between start and end valued and nodes used for calculation</h3>

    @foreach (var calculationInformation in Model.SequenceCalculationInformation)
    {
        <div>@calculationInformation.Machine , @calculationInformation.Number.ToString("N0")</div>
    }
</div>

Web/Startup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fibonacci numbers</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Main</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Sequence" asp-action="Index">Sequence</a>
                </li>
            </ul>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer></footer>
</body>
</html>